### ISSUE TITLE
[Migrated issue | sirius_signal_lights_driver] Separate Code for Controlling Signal Lights and Deducting Robot Status

### ISSUE THREAD

**Issue by Wihmajster** [SKA-Robotics/sirius_robot#3]
This is a migrated issue and refers only to sirius_signal_lights_driver package
---
Deducting robot status seems to be a universal task, not limited to signal lights. Consider creating a dedicated node in the `sirius_control` package within the [`sirius_common` repository](https://github.com/SKA-Robotics/sirius_common) that will generate the [`RobotStatus` message](https://docs.ros.org/en/noetic/api/industrial_msgs/html/msg/RobotStatus.html). This message is designed for robotic manipulators using the ROS industrial ecosystem, but we can adapt it for our robot without losing its semantic meaning. The only exception would be the `RobotMode` field, where "Auto" also refers to teleoperation. In our case, "manual" mode would represent teleoperation and "auto" would represent autonomous mode. Although this is a misuse of the message, clarifying it in the documentation should prevent misunderstandings. This can serve as a good starting point, and we can improve or potentially create our own message for mobile robots in the future.

The `RobotStatus` message could then be used by the web interface and signal lights. Since signal lights can already be controlled by ROS messages via the `socketcan_bridge` package, there is no need to create an additional interface. Therefore, a node controlling the lights would directly subscribe to the `RobotStatus` message and send appropriate CAN messages based on user configuration. An optimal format for user configuration could look like this:
```yaml
blue: # Autonomous mode
    status: # Light will be enabled when robot status matches this configuration
        mode: auto
        e_stopped: false
        # other settings are not declared if their value does not matter for this light
    some_other_important_settings_if_any: some important value 
red: # Motors powered
    status:
        e_stopped: false
        drives_powered: true
yellow: # Teleoperation
    status:
        mode: manual
        e_stopped: false
        motion_possible: true
```

If this version suits you, I also recommend renaming the package for controlling the signal lights to "sirius_signal_lights_driver" or "sirius_indicator_driver." The "sirius" prefix and "driver" suffix would better match the [REP 144](https://ros.org/reps/rep-0144.html) recommendations.
